name: Make Release

on:
  push:
    branches: [master]

jobs:
  untagged-release:
    name: "Untagged Release"
    runs-on: "windows-latest"
    env:
      version: processing-3.5.4

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup Processing
        uses: carlosperate/download-file-action@v1.0.3
        with:
          file-url: https://download.processing.org/${{ env.version }}-windows64.zip
      - run: 7z x -y .\${{ env.version }}-windows64.zip

      - name: Download Sound Library
        uses: MrOctopus/download-asset-action@main
        with:
          repository: processing/processing-sound
          asset: sound.zip
          target: .\code
      - name: Unpack Sound Library
        run: |
          cd ${{ github.workspace }}
          mkdir licenses
          cd code
          7z e -y sound.zip sound/library
          cd ${{ github.workspace }}/licenses
          mkdir sound
          cd sound
          7z e -y ${{ github.workspace }}\code\sound.zip sound/LICENSE sound/README.md
          cd ${{ github.workspace }}

      - name: Download minim
        uses: actions/checkout@v2
        with:
          repository: ddf/Minim
          path: 'Minim'
      - name: Unpack Minim
        run: |
          cd ${{ github.workspace }}
          Copy-Item -Path "${{ github.workspace }}\Minim\library\*" -Destination "${{ github.workspace }}\code"
          cd licenses
          mkdir minim
          Copy-Item -Path "${{ github.workspace }}\Minim\license.txt" -Destination "${{ github.workspace }}\licenses\minim"
          Copy-Item -Path "${{ github.workspace }}\Minim\README.md" -Destination "${{ github.workspace }}\licenses\minim"
          cd ${{ github.workspace }}

      - name: Copy Font Licenses
        # https://superuser.com/a/1263489
        run: |
          Get-ChildItem -Path "${{ github.workspace }}\data\Fonts\*" -Include *txt -Recurse | Copy-Item -Destination "${{ github.workspace }}\licenses"

      - name: Run Build
        run: |
          ${{ github.workspace }}\${{ env.version }}\processing-java.exe --sketch="${{ github.workspace }}" --output="${{ github.workspace }}\build" --export --platform 'windows'

      - name: Zip Build
        run: |
          cd ${{ github.workspace }}
          mkdir build\licenses
          XCopy /E /I ${{ github.workspace }}\licenses ${{ github.workspace }}\build\licenses
          7z a Asteroids-Win.zip ./build/*
          7z a Licenses.zip ./licenses/*

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          automatic_release_tag: latest
          files: |
            SpaceLovers-Win.zip
            Licenses.zip
