name: Make Release

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "windows-latest"
    env:
      version: processing-3.5.4

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup Processing
        uses: carlosperate/download-file-action@v1.0.3
        with:
          file-url: https://download.processing.org/${{ env.version }}-windows64.zip
      - run: 7z x -y .\${{ env.version }}-windows64.zip

      - name: Download Sound Library
        uses: MrOctopus/download-asset-action@main
        with:
          repository: processing/processing-sound
          asset: sound.zip
          target: .\code
      - name: Unpack Sound Library
      - run: |
          cd ${{ github.workspace }}
          mkdir licenses
          cd code
          7z e -y sound.zip sound/library
          cd ../licenses
          mkdir sound
          cd sound
          7z e -y ../../code/sound.zip LICENSE README.md
          cd ${{ github.workspace }}

      - name: Run Build
        run: |
          ${{ github.workspace }}\${{ env.version }}\processing-java.exe --sketch="${{ github.workspace }}" --output="${{ github.workspace }}\build" --export --platform 'windows'

      - name: Zip Build
        run: |
          cd ${{ github.workspace }}
          XCopy /E /I ${{ github.workspace }}\licenses ${{ github.workspace }}\build 
          7z a Asteroids-Win.zip ./build/*
          7z a Licenses.zip ./licenses/*

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            Asteroids-Win.zip
            Licenses.zip
