# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Try Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Download Processing
      uses: carlosperate/download-file-action@v1.0.3
        with:
          file-url: https://download.processing.org/processing-3.5.4-windows64.zip
    - name: Unzip Processing
      run: 7z x -y .\processing-3.5.4-windows64.zip

    - name: List Directory
      run: ls ${{ github.workspace }}

    - uses: benthillerkus/processing-problem-matcher@master
    - name: Build
      run: "${{ github.workspace }}\\processing-3.5.4\\processing-java-exe" --sketch="${{ github.workspace }}" --build
