# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Try Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    env:
      version: processing-3.5.4

    steps:
    - uses: actions/checkout@v2
    - name: Setup Processing
      uses: carlosperate/download-file-action@v1.0.3
      with:
        file-url: https://download.processing.org/${{ env.version }}-windows64.zip
    - run: 7z x -y .\${{ env.version }}-windows64.zip

    - name: List Directory
      run: ls ${{ github.workspace }}

    - uses: benthillerkus/processing-problem-matcher@master
    - name: Build
      run: |
        ${{ github.workspace }}\${{ env.version }}\processing-java.exe --sketch="${{ github.workspace }}" --build
