# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Try Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Processing
      run: choco install processing

    - name: List Directory
      run: ls ${{ github.workspace }}

    - uses: benthillerkus/processing-problem-matcher@master
    - name: Build
      run: processing-java --sketch="${{ github.workspace }}" --build
