# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Try Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Processing
      uses: engineerd/configurator@v0.0.6
      with:
        name: "processing-java.exe"
        url: "https://download.processing.org/processing-3.5.4-linux64.tgz"
        pathInArchive: "processing-3.5.4/processing-java"

    - name: List Directory
      run: ls ${{ github.workspace }}

    - name: Build
      run: |
        processing-java --sketch="${{ github.workspace }}" --build
