# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Check Build

on:
  pull_request:

jobs:
  build:
    name: "Check Build"
    runs-on: windows-latest
    env:
      version: processing-3.5.4

    steps:
      - uses: actions/checkout@v2
      - name: Setup Processing
        uses: carlosperate/download-file-action@v1.0.3
        with:
          file-url: https://download.processing.org/${{ env.version }}-windows64.zip
      - run: 7z x -y .\${{ env.version }}-windows64.zip

      - name: Download Sound Library
        uses: MrOctopus/download-asset-action@main
        with:
          repository: processing/processing-sound
          asset: sound.zip
          target: .\code
      - name: Unpack Sound Library
        run: |
          cd ${{ github.workspace }}
          mkdir licenses
          cd code
          7z e -y sound.zip sound/library
          cd ${{ github.workspace }}\licenses
          mkdir sound
          cd sound
          7z e -y ${{ github.workspace }}\code\sound.zip sound/LICENSE sound/README.md
          cd ${{ github.workspace }}

      - name: List Directory
        run: ls -R ${{ github.workspace }}

      - uses: benthillerkus/processing-problem-matcher@master
      - name: Run Build
        run: |
          ${{ github.workspace }}\${{ env.version }}\processing-java.exe --sketch="${{ github.workspace }}" --build
